name = "Massucci2013"
uuid = "9fd1272b-efb0-4a54-9bd1-5eb94b19cd3d"
authors = ["josePereiro <jose.pereiro.pereiro@gmail.com> and <irael000923@gmail.com>"]
version = "0.1.0"

[deps]
COBREXA = "babc4406-5200-4a30-9033-bf5ae714c842"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
